export default {
	namespaced:true,
	state:{
		address:JSON.parse(uni.getStorageSync('address')||'{}'),
		token:uni.getStorageSync('token')||'',
		userInfo:JSON.parse(uni.getStorageSync('userInfo')||'{}'),
	},
	mutations:{
		addAddress(state,address){
			state.address=address
			this.commit('userInfo/saveAddressToStorage')
		},
		saveAddressToStorage(state){
			uni.setStorageSync('address',JSON.stringify(state.address))
		},
		updateUserInfo(state,userInfo){
			state.userInfo=userInfo
			this.commit('userInfo/saveUserInfoToStorage')
		},
		saveUserInfoToStorage(state){
			uni.setStorageSync('userInfo',JSON.stringify(state.userInfo))
		},
		setToken(state,token){
			state.token=token
			this.commit('userInfo/saveTokenToStorage')
		},
		saveTokenToStorage(state){
			uni.setStorageSync('token',JSON.stringify(state.token))
		}
	},
	getters:{
		addressInfo(state){
			return state.address.provinceName+state.address.cityName+state.address.countyName+state.address.detailInfoNew
		}
	}
}